### ISSUE TITLE
Go Meta Linter

### ISSUE THREAD

**Issue by ptman** [divan/depscheck#2]
Would it make sense to work with [gometalinter](https://github.com/alecthomas/gometalinter) to get this included in the tests it can run?

**Comment by divan** [comment]
I was thinking about it too, but rejected the idea so far because it's recommendation only and is probably prone to false alarms. Also, I don't like noisy linters, so don't want to add another one to gometalinter.

But it's relatively easy to add 'linter mode'. If this feature will be demanded by more people, I'll add it for sure.
